cdi-unit/pom.xml
Rev ```reflections``` to ```0.9.10```.  This also cleans up some questionable transitive deps from 'reflections'
=> Update to release version of 'reflections'

.travis.yml, README.md, cdi-unit-tests-bare/pom.xml, cdi-unit-tests-easymock/pom.xml, cdi-unit-tests-external-dependency/pom.xml, cdi-unit-tests-gradle/pom.xml, cdi-unit-tests-jandex/pom.xml, cdi-unit-tests-mockito/pom.xml, cdi-unit-tests/pom.xml, cdi-unit-tests/src/test/java/org/jglue/cdiunit/TestContextController.java, cdi-unit/pom.xml, cdi-unit/src/main/java/org/jglue/cdiunit/CdiRunner.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/WeldTestUrlDeployment.java, logback-maven.xml, pom.xml
See commit history for a full list of updates.
I would like to use this as a base for implementing support of JUnit 5 (issue #103)  when junit-team/junit5#672 has been implemented.
Should also fix #98  and #101
=> Framework upgrades

cdi-unit/src/main/java/org/jglue/cdiunit/CdiRunner.java
=> Restore context factory

.travis.yml, cdi-unit-tests-bare/pom.xml, cdi-unit-tests-easymock/pom.xml, cdi-unit-tests-external-dependency/pom.xml, cdi-unit-tests-gradle/pom.xml, cdi-unit-tests-jandex/pom.xml, cdi-unit-tests-mockito/pom.xml, cdi-unit-tests/pom.xml, cdi-unit/pom.xml, cdi-unit/src/main/java/org/jglue/cdiunit/internal/CdiUnitInitialListener.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/CdiUnitInitialListenerImpl.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/CdiUnitInitialListenerImpl11.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/CdiUnitInitialListenerProducer.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/WeldTestUrlDeployment.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/ejb/DefaultLiteral.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/ejb/EjbExtension.java, pom.xml, test-multi.sh
For https://github.com/BrynCooke/cdi-unit/issues/112
=> Support Weld 3.0

.travis.yml, cdi-unit/src/main/java/org/jglue/cdiunit/internal/WeldTestUrlDeployment.java, docs/index.md, pom.xml
Addresses #120.
Still to do:
- ~~Add jar manifest entry for Add-Opens~~ - only applies to executable jars
=> Add basic support for Java 9

.travis.yml
See https://github.com/travis-ci/travis-ci/issues/10055
=> Use sudo:true as workaround for Travis issue

cdi-unit/pom.xml, pom.xml
=> Update dependency versions - 2020-04

cdi-unit/src/main/java/org/jglue/cdiunit/IgnoredClasses.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/WeldTestUrlDeployment.java, cdi-unit/src/test/java/org/jglue/cdiunit/TestIgnoreClasses.java, docs/index.md
Allow classes to be explicitly ignored - rebase PR #147 after build repairs
Fix for #146
=> Allow classes to be explicitly ignored - rebase #147 after build repairs

cdi-unit-tests-testng/pom.xml, cdi-unit-tests-testng/src/main/resources/META-INF/beans.xml, cdi-unit-tests-testng/src/test/java/org/jglue/cdiunit/tests/testng/AImplementation1.java, cdi-unit-tests-testng/src/test/java/org/jglue/cdiunit/tests/testng/AInterface.java, cdi-unit-tests-testng/src/test/java/org/jglue/cdiunit/tests/testng/ASuper.java, cdi-unit-tests-testng/src/test/java/org/jglue/cdiunit/tests/testng/TestNgCdiRunner.java, cdi-unit-tests-testng/src/test/java/org/jglue/cdiunit/tests/testng/TestNgProducerConfig.java, cdi-unit-tests-testng/src/test/java/org/jglue/cdiunit/tests/testng/package-info.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/DefaultBeanArchiveScanner.java, cdi-unit/src/main/resources/META-INF/org.jglue.cdiunit-archive, pom.xml
Repair TestNG run without JUnit dependencies
Supersedes PR #155
=> Repair TestNG run without JUnit dependencies

cdi-unit/src/test/java/org/jglue/cdiunit/TestJaxRs.java
Repairs for No active contexts for scope type javax.enterprise.context.RequestScoped with @SupportJaxRs #133
=> Repairs for No active contexts for scope type javax.enterprise.context.RequestScoped with @SupportJaxRs #133

cdi-unit-tests/src/test/java/org/jglue/cdiunit/TestCdiUnitRunner.java, cdi-unit/src/main/java/org/jglue/cdiunit/AdditionalClasses.java, cdi-unit/src/main/java/org/jglue/cdiunit/AdditionalClasspaths.java, cdi-unit/src/main/java/org/jglue/cdiunit/AdditionalPackages.java, cdi-unit/src/main/java/org/jglue/cdiunit/ContextController.java, cdi-unit/src/main/java/org/jglue/cdiunit/IgnoredClasses.java, cdi-unit/src/main/java/org/jglue/cdiunit/IsolationLevel.java, cdi-unit/src/main/java/org/jglue/cdiunit/NgCdiRunner.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/CachingClassGraphScanner.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/CdiUnitInitialListener.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/TestConfiguration.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/servlet/MockHttpServletRequestImpl.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/servlet/MockHttpServletResponseImpl.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/servlet/MockHttpSessionImpl.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/servlet/MockRequestDispatcher.java, cdi-unit/src/main/java/org/jglue/cdiunit/internal/servlet/MockServletContextImpl.java, cdi-unit/src/test/java/org/jglue/cdiunit/TestCdiUnitRunner.java
No semantical changes expected / introduced
=> Unify code formatting and indentation in Java classes

cdi-unit/src/test/java/org/jglue/cdiunit/TestJUnitRule.java
=> Add example of the JUnit rule usage

.github/workflows/maven.yml, travisci/weld-v3.1.sh
Use GitHub Actions to test Zulu JDK 11 issues
See #182 
I could not find an easy way to test this on TravisCI.
=> Use GitHub Actions to test Zulu JDK 11 issues

ci-support/deltaspike-v1.x.sh
=> chore: Update Deltaspike test matrix

cdi-unit-tests-bare/pom.xml, cdi-unit-tests-deltaspike/pom.xml, cdi-unit-tests-easymock/pom.xml, cdi-unit-tests-external-dependency/pom.xml, cdi-unit-tests-gradle/pom.xml, cdi-unit-tests-jandex/pom.xml, cdi-unit-tests-mockito/pom.xml, cdi-unit-tests-parent/pom.xml, cdi-unit-tests-testng/pom.xml, cdi-unit-tests/pom.xml, cdi-unit/pom.xml, pom.xml
=> build: Embed relevant content from the oss-parents

.gitignore, README.md, cdi-unit-tests-bare/pom.xml, cdi-unit-tests-deltaspike/pom.xml, cdi-unit-tests-easymock/pom.xml, cdi-unit-tests-external-dependency/pom.xml, cdi-unit-tests-gradle/pom.xml, cdi-unit-tests-jandex/pom.xml, cdi-unit-tests-mockito/pom.xml, cdi-unit-tests-parent/pom.xml, cdi-unit-tests-testng/pom.xml, cdi-unit-tests/pom.xml, cdi-unit/pom.xml, docs/index.md, make-release.sh, pom.xml
=> chore: Move to new group ID: io.github.cdi-unit

.github/workflows/build-test-temurin.yml, .github/workflows/build-test-zulujdk.yml, .gitignore, ci-support/build.sh, ci-support/test-deltaspike.sh, ci-support/test-weld.sh, independent-projects/ide-config/pom.xml, independent-projects/ide-config/src/main/resources/cdi-unit-format.xml, independent-projects/ide-config/src/main/resources/eclipse.importorder, pom.xml, versions-ignored.xml
This PR introduces configuration for the automated formatting and imports sorting.
The formatting and validation is NOT enforced yet.
=> chore: Infrastructure for formatting and import sorting

build-parent/pom.xml, core/pom.xml, core/src/main/java/io/github/cdiunit/internal/ClassLookup.java, docs/index.md, support-deltaspike/pom.xml, support-deltaspike/src/main/java/io/github/cdiunit/internal/deltaspike/DeltaspikeScopeDiscoveryExtension.java, support-deltaspike/src/main/resources/META-INF/services/io.github.cdiunit.internal.DiscoveryExtension, support-deltaspike/src/test/java/io/github/cdiunit/deltaspike/TestWindowScoped.java, support-deltaspike/src/test/java/io/github/cdiunit/deltaspike/WindowScopedBeanX.java
=> feat: Add support for DeltaSpike's WindowScoped

core/src/main/java/io/github/cdiunit/internal/resource/InjectAtResourceExtension.java, core/src/main/java/io/github/cdiunit/resource/SupportResource.java, core/src/test/java/io/github/cdiunit/TestResource.java, docs/index.md, integration-tests/tests/src/test/java/io/github/cdiunit/TestResource.java
=> feat: Add support for @Resource injection.

core/src/main/java/io/github/cdiunit/CdiJUnit.java, core/src/main/java/io/github/cdiunit/CdiRunner.java, core/src/main/java/io/github/cdiunit/NgCdiListener.java, core/src/main/java/io/github/cdiunit/internal/junit4/ActivateScopes.java, core/src/main/java/io/github/cdiunit/internal/junit4/BeanLifecycle.java, core/src/main/java/io/github/cdiunit/internal/junit4/CdiJUnitRule.java, core/src/main/java/io/github/cdiunit/internal/junit4/JUnitInvocationContext.java, core/src/main/java/io/github/cdiunit/internal/junit4/NamingContextLifecycle.java, core/src/main/java/io/github/cdiunit/internal/junit4/WeldLifecycle.java, core/src/main/java/io/github/cdiunit/internal/junit4/package-info.java, core/src/test/java/io/github/cdiunit/TestCdiUnitRule.java, integration-tests/tests/src/test/java/io/github/cdiunit/TestCdiUnitRule.java
=> feat: Support JUnit 4 test rule

core/src/main/java/io/github/cdiunit/NgCdiListener.java, core/src/main/java/io/github/cdiunit/internal/BeanLifecycleHelper.java, core/src/main/java/io/github/cdiunit/internal/junit4/BeanLifecycle.java, core/src/test/java/io/github/cdiunit/testng/TestBasicFeatures.java, integration-tests/tests-testng/src/test/java/io/github/cdiunit/tests/testng/TestBasicFeatures.java
=> feat: Support test bean lifecycle callbacks in TestNG

core/src/main/java/io/github/cdiunit/internal/BeanLifecycleHelper.java, core/src/main/java/io/github/cdiunit/internal/WeldHelper.java, integration-tests/junit5-tests/src/test/java/io/github/cdiunit/junit5/tests/BasicFeaturesTestBase.java, integration-tests/junit5-tests/src/test/java/io/github/cdiunit/junit5/tests/TestBasicFeatures.java, integration-tests/junit5-tests/src/test/java/io/github/cdiunit/junit5/tests/TestNestedFeatures.java, junit5/src/main/java/io/github/cdiunit/junit5/CdiJUnit5Extension.java, junit5/src/main/java/io/github/cdiunit/junit5/internal/JUnit5InvocationContext.java, junit5/src/test/java/io/github/cdiunit/junit5/tests/BasicFeaturesTestBase.java, junit5/src/test/java/io/github/cdiunit/junit5/tests/TestBasicFeatures.java, junit5/src/test/java/io/github/cdiunit/junit5/tests/TestInstanceIsolation.java, junit5/src/test/java/io/github/cdiunit/junit5/tests/TestNestedFeatures.java
=> feat: Support for JUnit 5 Nested tests

core/src/main/java/io/github/cdiunit/CdiJUnit.java, core/src/main/java/io/github/cdiunit/internal/TestLifecycle.java, core/src/main/java/io/github/cdiunit/internal/junit4/CdiJUnitRule.java, core/src/test/java/io/github/cdiunit/junit4/ApplicationCounter.java, core/src/test/java/io/github/cdiunit/junit4/TestBasicFeatures.java, core/src/test/java/io/github/cdiunit/junit4/TestIsolationPerClass.java, core/src/test/java/io/github/cdiunit/junit4/TestIsolationPerMethod.java, core/src/test/java/io/github/cdiunit/junit4/TestNamingContext.java, core/src/test/java/io/github/cdiunit/junit4/TestProducerConfig.java, integration-tests/tests/src/test/java/io/github/cdiunit/TestCdiUnitRule.java
Addresses https://github.com/cdi-unit/cdi-unit/issues/289 for JUnit 4 runner and rules.
=> feat: JUnit4 - Test isolation

core/src/main/java/io/github/cdiunit/NgCdiListener.java, core/src/main/java/io/github/cdiunit/NgCdiRunner.java, core/src/main/java/io/github/cdiunit/internal/TestLifecycle.java, core/src/test/java/io/github/cdiunit/testng/ApplicationCounter.java, core/src/test/java/io/github/cdiunit/testng/BaseTest.java, core/src/test/java/io/github/cdiunit/testng/TestBasicFeatures.java, core/src/test/java/io/github/cdiunit/testng/TestIsolationPerClass.java, core/src/test/java/io/github/cdiunit/testng/TestIsolationPerMethod.java, core/src/test/java/io/github/cdiunit/testng/TestNamingContext.java, core/src/test/java/io/github/cdiunit/testng/TestProducerConfig.java, integration-tests/tests-testng/src/test/java/io/github/cdiunit/tests/testng/TestBasicFeatures.java, integration-tests/tests-testng/src/test/java/io/github/cdiunit/tests/testng/TestProducerConfig.java
=> feat: TestNG - Test isolation

core/src/main/java/io/github/cdiunit/internal/TestLifecycle.java, core/src/main/java/io/github/cdiunit/internal/events/EventsForwardingDiscoveryExtension.java, core/src/main/java/io/github/cdiunit/internal/events/EventsForwardingExtension.java, core/src/main/java/io/github/cdiunit/internal/events/ForwardedEvents.java, core/src/main/java/io/github/cdiunit/internal/events/ForwardingInterceptor.java, core/src/main/java/io/github/cdiunit/internal/events/package-info.java, core/src/main/resources/META-INF/services/io.github.cdiunit.internal.DiscoveryExtension, core/src/test/java/io/github/cdiunit/junit4/TestInstanceObserveEvents.java, core/src/test/java/io/github/cdiunit/testng/TestInstanceObserveEvents.java, junit5/src/test/java/io/github/cdiunit/junit5/tests/TestInstanceObserveEvents.java, junit5/src/test/java/io/github/cdiunit/junit5/tests/TestNestedFeatures.java
=> feat: Extension to invoke event observers on test instances not managed by CDI

core/src/test/java/io/github/cdiunit/junit4/TestBasicFeatures.java, integration-tests/junit5-tests/src/test/java/io/github/cdiunit/junit5/tests/BasicFeaturesTestBase.java, integration-tests/junit5-tests/src/test/java/io/github/cdiunit/junit5/tests/TestBasicFeatures.java, integration-tests/junit5-tests/src/test/java/io/github/cdiunit/junit5/tests/TestNestedFeatures.java, integration-tests/testng-tests/src/test/java/io/github/cdiunit/testng/tests/TestBasicFeatures.java, integration-tests/tests/src/test/java/io/github/cdiunit/TestCdiUnitRule.java, integration-tests/tests/src/test/java/io/github/cdiunit/TestCdiUnitRunner.java, junit5/src/test/java/io/github/cdiunit/junit5/tests/BasicFeaturesTestBase.java, junit5/src/test/java/io/github/cdiunit/junit5/tests/TestBasicFeatures.java, junit5/src/test/java/io/github/cdiunit/junit5/tests/TestNestedFeatures.java, testng/src/test/java/io/github/cdiunit/testng/TestBasicFeatures.java
=> fix: Repair failing tests for ProducedVia

.github/mvn-settings.xml, .github/project.yml, .github/workflows/release.yml
=> ci: Release workflow with GitHub Actions

.github/workflows/build-test-temurin-windows.yml, .github/workflows/build-test-temurin.yml, .github/workflows/build-test-zulujdk.yml, ci-support/weld-v5.1.sh, integration-tests/testng-tests/src/test/java/io/github/cdiunit/testng/tests/TestBasicFeatures.java
=> feat(weld): Support Weld 5.1.3.Final
